### ISSUE TITLE
mod-anticheat

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/catalogue#24]
Couldnt find the file to make a PR.

http://www.azerothcore.org/modules-catalogue/details.html?id=76854840

![image](https://user-images.githubusercontent.com/24550914/71562939-12599100-2a88-11ea-8589-884bebd48c7a.png)

Should add spaces before the 1)

### 1)

**Comment by Helias** [comment]
Because the missing spaces are in this repository https://github.com/azerothcore/mod-anticheat

Anyway, ty

**Comment by Helias** [comment]
Fixed https://github.com/azerothcore/mod-anticheat/commit/0cb8699e78974f0e9967f3e70403a028848ed6b4

thanks @Kitzunu
